name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Set CHROME_BIN env
        run: echo "CHROME_BIN=$(which google-chrome)" >> $GITHUB_ENV
      - name: Run tests
        run: yarn test
